server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true

spring:
  application:
    name: authentication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/demo
    username: postgres
    password: postgres
    tomcat:
      initial-size: 3
      min-idle: 3
      max-idle: 5
      max-active: 10
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      id: authentication

security:
  oauth2:
    authentication:
      tokenValiditySeconds: 43200 # 12 hour
      refreshTokenValiditySeconds: 2592000 # 30days
    resource:
      userInfoUri: http://localhost:8080/authentication/token/current
    client:
      clientId: authentication
      clientSecret: test

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          strategy: SEMAPHORE
