server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  instance:
    preferIpAddress: true

cors:
  allowedOrigins: "*"

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  retryable: true
  sensitive-headers:
